/**
 * Mock dataset for Manav Rachna University Event Portal Landing Page.
 * Used for development and standalone execution when Firebase is unconfigured.
 */

export const mockCollegeInfo = {
  name: "Manav Rachna University",
  address: "Sector 43, Aravalli Hills, Delhi-Surajkund Road, Faridabad, Haryana 121004, India",
  mapsQueryUrl: "https://www.google.com/maps/search/?api=1&query=Manav+Rachna+University+Sector+43+Aravalli+Hills+Delhi-Surajkund+Road+Faridabad+Haryana+121004+India",
};

export const mockCategories = [
  { id: "all", name: "All" },
  { id: "tech", name: "Tech & Hackathons" },
  { id: "cultural", name: "Cultural & Arts" },
  { id: "sports", name: "Sports & Fitness" },
  { id: "workshops", name: "Workshops & Seminars" },
  { id: "gaming", name: "Gaming & Esports" },
  { id: "entrepreneurship", name: "Entrepreneurship" },
];

export const mockOrganizers = [
  "IEEE",
  "IIC",
  "DSW",
  "GDSC",
  "CSI",
  "ACM",
  "NSS",
  "NCC",
  "E-Cell",
  "Other",
];

export const mockFeaturedEvents = [
  {
    id: "feat-1",
    title: "HackMRU 2026: AI & Future Tech",
    tagline: "Build cutting-edge AI applications with ₹1,00,000 in prizes",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80",
    detailUrl: "/events/feat-1",
    organizer: "IEEE",
    venue: "Main Auditorium, Block C",
    contactNumber: "+91 98765 43210",
    registrationType: "Free",
    fee: "Free",
    rawFee: 0,
    popularity: 980,
    date: "Aug 15, 2026",
    category: "Tech & Hackathons",
    categoryId: "tech",
    description: "HackMRU 2026 is the flagship annual hackathon of Manav Rachna University organized by IEEE Student Branch. Over 36 continuous hours, student innovators from across India will brainstorm, design, and prototype AI-driven solutions addressing real-world challenges in healthcare, education, and sustainability. Industry mentors and tech leads will be available on site.",
  },
  {
    id: "feat-2",
    title: "Annual Campus Spring Music Fest",
    tagline: "Live performances by top indie bands and guest DJs",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80",
    detailUrl: "/events/feat-2",
    organizer: "DSW",
    venue: "Open Air Theatre (OAT)",
    contactNumber: "+91 91234 56789",
    registrationType: "Paid",
    fee: "₹250",
    rawFee: 250,
    popularity: 1250,
    date: "Aug 28, 2026",
    category: "Cultural & Arts",
    categoryId: "cultural",
    description: "Experience an electric evening of music, rhythm, and passion at the Annual Campus Spring Music Fest hosted by DSW. Featuring headline performances by renowned indie bands, student acoustic sets, and high-energy DJ tracks under the stars.",
  },
  {
    id: "feat-3",
    title: "Venture Pitch Competition 2026",
    tagline: "Pitch your startup idea to NCR angel investors",
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80",
    detailUrl: "/events/feat-3",
    organizer: "E-Cell",
    venue: "Incubation Centre, Room 204",
    contactNumber: "+91 99887 76655",
    registrationType: "Free",
    fee: "Free",
    rawFee: 0,
    popularity: 840,
    date: "Aug 25, 2026",
    category: "Entrepreneurship",
    categoryId: "entrepreneurship",
    description: "The Entrepreneurship Cell brings you Venture Pitch 2026—a platform for student entrepreneurs to present scalable business models to prominent venture capitalists and angel investors. Top winning teams receive incubation support, mentorship grants, and office space.",
  },
];

export const mockEvents = [
  {
    id: "evt-101",
    name: "AI & Machine Learning Bootcamp",
    category: "Tech & Hackathons",
    categoryId: "tech",
    date: "Aug 15, 2026",
    fee: "Free",
    rawFee: 0,
    registrationType: "Free",
    organizer: "GDSC",
    venue: "Lab 3, T-Block, 2nd Floor",
    contactNumber: "+91 98765 11223",
    popularity: 920,
    createdAt: "2026-08-01T10:00:00Z",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80",
    description: "Join Google Developer Student Club for a hands-on intensive bootcamp on Deep Learning, PyTorch, and Computer Vision models. Participants will build and train their first neural network from scratch.",
  },
  {
    id: "evt-102",
    name: "Inter-College Esports Championship",
    category: "Gaming & Esports",
    categoryId: "gaming",
    date: "Aug 18, 2026",
    fee: "₹200",
    rawFee: 200,
    registrationType: "Paid",
    organizer: "CSI",
    venue: "Computer Centre Auditorium",
    contactNumber: "+91 98112 33445",
    popularity: 1100,
    createdAt: "2026-08-03T14:30:00Z",
    thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80",
    description: "Battle it out in Valorant, BGMI, and Rocket League at the largest inter-college esports tournament organized by CSI Student Chapter. Cash prizes worth ₹50,000 for top squads.",
  },
  {
    id: "evt-103",
    name: "UI/UX Design Masterclass",
    category: "Workshops & Seminars",
    categoryId: "workshops",
    date: "Aug 20, 2026",
    fee: "₹100",
    rawFee: 100,
    registrationType: "Paid",
    organizer: "ACM",
    venue: "Seminar Hall 1, Block B",
    contactNumber: "+91 99554 43322",
    popularity: 760,
    createdAt: "2026-08-05T09:15:00Z",
    thumbnail: "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&w=600&q=80",
    description: "Learn modern product design principles, wireframing in Figma, and design systems from senior product designers. Includes interactive workshop activities and portfolio reviews.",
  },
  {
    id: "evt-104",
    name: "Campus Basketball League Opening",
    category: "Sports & Fitness",
    categoryId: "sports",
    date: "Aug 22, 2026",
    fee: "Free",
    rawFee: 0,
    registrationType: "Free",
    organizer: "NCC",
    venue: "Outdoor Sports Complex Court 1",
    contactNumber: "+91 97112 23344",
    popularity: 640,
    createdAt: "2026-07-28T16:00:00Z",
    thumbnail: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=600&q=80",
    description: "Cheer for your department team as the Inter-Department Basketball League kicks off! Organized by NCC Cadets with live commentary and refreshment stalls.",
  },
  {
    id: "evt-105",
    name: "Startup Founders & Investor Night",
    category: "Entrepreneurship",
    categoryId: "entrepreneurship",
    date: "Aug 25, 2026",
    fee: "₹150",
    rawFee: 150,
    registrationType: "Paid",
    organizer: "E-Cell",
    venue: "Executive Lounge, Admin Block",
    contactNumber: "+91 98990 01122",
    popularity: 880,
    createdAt: "2026-08-04T18:00:00Z",
    thumbnail: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=600&q=80",
    description: "An exclusive networking event connecting student founders with seed-stage angel investors, incubators, and industry veterans. Dinner and refreshments provided.",
  },
  {
    id: "evt-106",
    name: "Acoustic Sunset Music Session",
    category: "Cultural & Arts",
    categoryId: "cultural",
    date: "Aug 28, 2026",
    fee: "Free",
    rawFee: 0,
    registrationType: "Free",
    organizer: "DSW",
    venue: "Central Lawns, Near Library",
    contactNumber: "+91 98711 55667",
    popularity: 1050,
    createdAt: "2026-08-02T11:45:00Z",
    thumbnail: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80",
    description: "Unwind on the central lawns with soulful acoustic performances, open mic poetry, and live unplugged music hosted by the Directorate of Student Welfare.",
  },
  {
    id: "evt-107",
    name: "Mega Blood Donation Drive",
    category: "Workshops & Seminars",
    categoryId: "workshops",
    date: "Sep 02, 2026",
    fee: "Free",
    rawFee: 0,
    registrationType: "Free",
    organizer: "NSS",
    venue: "Health Centre Hall",
    contactNumber: "+91 98100 44332",
    popularity: 540,
    createdAt: "2026-08-06T08:00:00Z",
    thumbnail: "https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=600&q=80",
    description: "NSS Student Unit in collaboration with Red Cross Society is organizing a university-wide Blood Donation Drive. Certificates and refreshment kits for all donors.",
  },
  {
    id: "evt-108",
    name: "Research & Innovation Conclave",
    category: "Workshops & Seminars",
    categoryId: "workshops",
    date: "Sep 05, 2026",
    fee: "Free",
    rawFee: 0,
    registrationType: "Free",
    organizer: "IIC",
    venue: "Convention Centre Main Hall",
    contactNumber: "+91 99112 23344",
    popularity: 710,
    createdAt: "2026-08-06T12:00:00Z",
    thumbnail: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=600&q=80",
    description: "Institution's Innovation Council (IIC) presents the Annual Research Conclave featuring keynote talks by eminent scientists, patent filing workshops, and paper presentations.",
  },
];
